---
- name: Remediate EKS cluster security group
  hosts: localhost
  gather_facts: false
  vars_files: variables.yml
  tasks:
    - name: EKS Cluster information
      describe_eks_cluster:
        region: "{{ region }}"
        cluster_name: "{{ cluster_name }}"
      register: eks_cluster

    - name: Filter SG Allow Only Ingress 443 TCP
      filter_sg_allow_only_ingress_443:
        region: "{{ region }}"
        list_sg_ids: "{{ item.securityGroupIds }}"
      with_items:
        - "{{ securityGroupIds: eks_cluster['resourcesVpcConfig']['securityGroupIds'] }}"